HTML/CSS & JavaScript capstone project - Conference page
fbclh/capstone-one pull request #1
Opened 2021-12-23 15:00 UTC by fbclh

**Project requirements:**

- Personalize the content of your page and choose a topic that is different than the one in the original design.

- The pages should look almost identical to the original design, small adjustments like text or image changes are acceptable.

- You should build only these 2 pages: The home page and the about page. Each of these pages should have versions for 2 different screen sizes: Mobile: up to 768px wide and Desktop: 768px or wider.

- The home page should have a link in the menu to the about page and the logo in the header links to the home page.
Mobile menu.

- When the user clicks (or taps) the hamburger button on the header, the mobile menu appears over the page.The mobile menu should have a close (X) button that closes the menu.

- You should use a JavaScript variable with the data about the speakers and use it when the page loads to create the HTML for this section dynamically.

2021-12-23 20:10 UTC, leolpaz requested changes
Hi @fbclh , 

You've done an amazing job so far, I'd like to highlight the following:
- Organized code
- Good README
- Linters is passing

Some issues need to be resolved before your approval, but you're almost there!

<img src="https://media0.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>


## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-23 20:10 UTC, leolpaz commented on index.html
> +            ><img class="nav-bottom__logo" src="img/fintech-logo-1.svg" alt=""
- [ ] For accessibility kindly add an alt attribute, with a 1 or 2 word name for the image, kindly do this for all `<img>` elements
![image](https://user-images.githubusercontent.com/73140461/147286685-883ec8cf-fa40-476e-ab94-089bdb2ed742.png)

2021-12-23 20:10 UTC, leolpaz commented on README.md
> +This project is [MIT](./MIT.md) licensed.
- [ ] Kindly fix the link for the MIT license, I can see that you have the license, but clicking here leads to a 404, I imagine that's due to the naming being different than the link here

2021-12-24 02:16 UTC, fbclh commented
Hello there and thanks for your feedback! I have made the required change based on your review.

- All the brokers links has been fixed: (In case you get an Error 404 than is not the code because I test and retested it, it has something to do with GitHub Pages. And and I am more than happy to record another Loom and show that everything is working fine.)
- Mobile menu has been fixed.
- There is one nav link that you can click to go back to the home page.
- Add alt attribute to all img elements.
- The link for the MIT license has been fixed.

2021-12-24 03:49 UTC, julie-ify requested changes
## Hi @fbclh, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 # Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-24 03:49 UTC, julie-ify commented on pages/about.html
> +          </li>
- [ ] As mentioned by the previous reviewer, the about page still crashes when the user navigates to the about page on the desktop and click on the about page navigation link again. I received a `404 error` when I tried it on your deployed pages and received a `page not found` when I cloned your project.

See the error messages below:
<img width="765" alt="Loom_ANWANwAjRY" src="https://user-images.githubusercontent.com/81468675/147311597-73560c57-589c-4df9-a675-c0875455c672.png">

<img width="564" alt="Loom_wQfj2cxzrW" src="https://user-images.githubusercontent.com/81468675/147311622-f30535d1-4bd3-49a2-a9f2-73e0351af263.png">

2021-12-24 03:49 UTC, julie-ify commented on pages/about.html
> +          </li>
- [ ] After going through your code, I found the cause of the `404 error`. When you are in the about.html which is inside the pages folder, the path to the about page should be `href="about.html"` instead of `href="../pages/about.html"`. This is because you are in the current directory and inside the about.html file which is inside the pages folder. Once you make the below suggested changes, your web pages will not crash again. Please give it a try okay?

```suggestion
          <li class="nav__mobile-list">
            <a class="nav__mobile-links" href="about.html">About</a>
          </li>
```

2021-12-24 03:49 UTC, julie-ify commented on pages/about.html
> +            </li>
- [ ] Consider fixing this path too so that your web page will work as expected and not crash 😄

```suggestion
            <li>
              <a class="nav__a" href="about.html">About</a>
            </li>
```

2021-12-24 06:07 UTC, fbclh commented
Hello thanks for your feedback and pointing out the issue! I have made the required change based on your review.

- Replace <a class="nav__mobile-links" href="../pages/about.html">About</a> to <a class="nav__mobile-links" href="about.html">About</a>
- Replace <a class="nav__a" href="pages/about.html">About</a> to <a class="nav__a" href="about.html">About</a>

2021-12-24 06:28 UTC, ShoiraTa reviewed
### **STATUS: APPROVED  ✔️** 
------
Hi @fbclh,  

Your project is complete! Congratulations!  🎉💯🌟 
All the issues noted by previous reviewers were addressed 👍🏻 

<img src="https://www.serialminds.com/wp-content/uploads/2015/11/loser.gif" width="400" height="250" />

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-24 06:28 UTC, ShoiraTa commented on index.html
> +          </button>
- [ ] [OPTIONAL] I have noticed that more button is present on mobile and desktop sizes, however in both cases it does not function. I kindly suggest you to make this button work as expected, and make it invisible for desktop size for the next milestone 😉

2021-12-24 06:28 UTC, ShoiraTa commented on index.html
> +        </button>
- [ ] [OPTIONAL] When the aside menu is open, users can still scroll the body section of the website. To avoid this situation, you can easily set the `body{ overflow: hidden }` when users click on hamburger button, and when users close the aside `menu: body{ overflow: auto; `}  👍🏻

2021-12-24 06:55 UTC, merged